[versions]
kotlin = "2.3.10"
xml = "1.0.0-rc2"
ktor = "3.4.2"
testBalloon = "1.0.0-K2.3.0"

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serial = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version = "9.4.1" }
test = { id = "de.infix.testBalloon", version.ref = "testBalloon" }


[libraries]
xml = { module = "io.github.pdvrieze.xmlutil:core", version.ref = "xml" }
xml-serial = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xml" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.7.1" }
cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version = "0.3.6" }
json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.11.0" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-engine = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-cn = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serial = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
logger = { module = "ch.qos.logback:logback-classic", version = "1.5.6" }

test-core = { module = "de.infix.testBalloon:testBalloon-framework-core", version.ref = "testBalloon" }
test-kotest = { module = "de.infix.testBalloon:testBalloon-integration-kotest-assertions", version.ref = "testBalloon" }

[bundles]
ktor = ["ktor-core", "ktor-engine", "ktor-cn", "ktor-serial", "ktor-logging", "logger"]